name: build CI

on:
    push:
        branches: main
    workflow_dispatch:
    workflow_call:

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest,ubuntu-24.04,windows-latest,macos-13]
                arch: [x86,x64,arm64]
        runs-on: ${{matrix.os}}
        steps:
        - uses: actions/checkout@v4
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.9.13'
            architecture: ${{matrix.arch}}
            cache: 'pip' 
            cache-dependency-path: '**/requirements.txt'
        - name: Cache apt dependencies(for linux)
          if: ${{runner.os == 'Linux'}}
          uses: awalsh128/cache-apt-pkgs-action@latest 
          with: 
            packages: python3-tk 
            execute_install_scripts: true
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: Build
          run: pyinstaller -F --hidden-import=PIL._tkinter_finder --additional-hooks-dir=hooks main.py -n blind-bot -i .res/icon.ico
        - name: pack
          run: 7z a -tzip vcbots-bili-${{runner.os}}-${{matrix.arch}}.zip ./dist
        - name: Upload
          uses: actions/upload-artifact@v4
          with: 
            name: build-${{matrix.os}}-${{matrix.arch}}
            path: ./vcbots-bili-${{runner.os}}-${{matrix.arch}}.zip